# Generated by Django 3.1.3 on 2020-11-15 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nazwa')),
                ('code', models.CharField(max_length=4, verbose_name='Skrót')),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ('name', 'code'),
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entryCode', models.CharField(max_length=7, verbose_name='Kod')),
                ('name', models.CharField(max_length=30, verbose_name='Nazwa')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Czas dodania')),
                ('domestic', models.BooleanField(default=True, verbose_name='Liga krajowa')),
            ],
            options={
                'ordering': ('-created', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Dyscyplina')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Czas dodania')),
            ],
            options={
                'ordering': ('-created', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Czas dodania')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='teams.country')),
                ('league', models.ManyToManyField(to='teams.League', verbose_name='Liga')),
            ],
            options={
                'ordering': ('-created', 'name'),
            },
        ),
        migrations.AddField(
            model_name='league',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to='teams.sport', verbose_name='Dyscyplina'),
        ),
    ]
