# Generated by Django 3.1.3 on 2020-11-15 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('teams', '0001_initial'), ('teams', '0002_auto_20201115_1652'), ('teams', '0003_auto_20201115_1736'), ('teams', '0004_auto_20201115_1749'), ('teams', '0005_match_tournament'), ('teams', '0006_tournament_finished'), ('teams', '0007_auto_20201115_2007'), ('teams', '0008_contestant_sport'), ('teams', '0009_match_finished')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nazwa')),
                ('code', models.CharField(max_length=4, verbose_name='Skrót')),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ('name', 'code'),
            },
        ),
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Czas dodania')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='teams.country', verbose_name='Kraj pochodzenia')),
                ('sport', models.CharField(choices=[('FOOTBALL', 'Piłka nożna'), ('VOLLEYBALL', 'Siatkówka'), ('TENNIS', 'Tenis')], default='FOOTBALL', max_length=15, verbose_name='Dyscyplina')),
            ],
            options={
                'ordering': ('-created', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nazwa')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Czas dodania')),
                ('sport', models.CharField(choices=[('FOOTBALL', 'Piłka nożna'), ('VOLLEYBALL', 'Siatkówka'), ('TENNIS', 'Tenis')], default='FOOTBALL', max_length=15, verbose_name='Dyscyplina')),
                ('domestic', models.BooleanField(default=True, verbose_name='Liga krajowa')),
                ('finished', models.BooleanField(default=False, verbose_name='Ukończony')),
                ('contestants', models.ManyToManyField(blank=True, to='teams.Contestant', verbose_name='Uczestnicy')),
            ],
            options={
                'ordering': ('-created', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfStart', models.DateTimeField(verbose_name='Czas rozpoczęcia')),
                ('playerOneResult', models.PositiveIntegerField(default=0, verbose_name='Wynik zawodnika 1')),
                ('playerTwoResult', models.PositiveIntegerField(default=0, verbose_name='Wynik zawodnika 2')),
                ('outcome', models.CharField(choices=[('N', 'N'), ('1', '1'), ('2', '2'), ('X', 'X')], default='N', max_length=1, verbose_name='Rezultat')),
                ('playerOne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playerOnes', to='teams.contestant', verbose_name='Zawodnik 1')),
                ('playerTwo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playerTwos', to='teams.contestant', verbose_name='Zawodnik 2')),
                ('tournament', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teams.tournament', verbose_name='Zawody')),
                ('finished', models.BooleanField(default=False, verbose_name='Zakończony')),
            ],
            options={
                'ordering': ('-dateOfStart',),
                'verbose_name_plural': 'Matches',
            },
        ),
    ]
