# Generated by Django 3.1.3 on 2020-11-16 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_squashed_0009_match_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='sport',
            field=models.CharField(choices=[('FOOTBALL', 'Piłka nożna'), ('VOLLEYBALL', 'Siatkówka'), ('TENNIS', 'Tenis')], default='FOOTBALL', max_length=15, verbose_name='Dyscyplina'),
        ),
        migrations.AlterField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.tournament', verbose_name='Zawody'),
        ),
    ]
