# Generated by Django 3.1.3 on 2020-11-15 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nazwa')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Czas dodania')),
                ('domestic', models.BooleanField(default=True, verbose_name='Liga krajowa')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to='teams.sport', verbose_name='Dyscyplina')),
            ],
            options={
                'ordering': ('-created', 'name'),
            },
        ),
        migrations.RenameModel(
            old_name='Team',
            new_name='Contestant',
        ),
        migrations.DeleteModel(
            name='League',
        ),
        migrations.AlterField(
            model_name='contestant',
            name='league',
            field=models.ManyToManyField(to='teams.Competition', verbose_name='Liga'),
        ),
    ]
