# Generated by Django 3.1.3 on 2020-11-15 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20201115_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfStart', models.DateTimeField(verbose_name='Czas rozpoczęcia')),
                ('playerOneResult', models.PositiveIntegerField(default=0, verbose_name='Wynik zawodnika 1')),
                ('playerTwoResult', models.PositiveIntegerField(default=0, verbose_name='Wynik zawodnika 2')),
                ('outcome', models.CharField(choices=[('1', '1'), ('2', '2'), ('X', 'X')], default='X', max_length=1, verbose_name='Rezultat')),
                ('playerOne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playerOnes', to='teams.contestant', verbose_name='Zawodnik 1')),
                ('playerTwo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playerTwos', to='teams.contestant', verbose_name='Zawodnik 2')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nazwa')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Czas dodania')),
                ('sport', models.CharField(choices=[('FOOTBALL', 'Piłka nożna'), ('VOLLEYBALL', 'Siatkówka'), ('TENNIS', 'Tenis')], default='FOOTBALL', max_length=15, verbose_name='Dyscyplina')),
                ('domestic', models.BooleanField(default=True, verbose_name='Liga krajowa')),
            ],
            options={
                'ordering': ('-created', 'name'),
            },
        ),
        migrations.DeleteModel(
            name='Competition',
        ),
        migrations.DeleteModel(
            name='Sport',
        ),
        migrations.AlterField(
            model_name='contestant',
            name='league',
            field=models.ManyToManyField(to='teams.Tournament', verbose_name='Liga'),
        ),
    ]
