# Generated by Django 3.1.3 on 2020-11-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20201115_1736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ('-dateOfStart',), 'verbose_name_plural': 'Matches'},
        ),
        migrations.RemoveField(
            model_name='contestant',
            name='league',
        ),
        migrations.AddField(
            model_name='tournament',
            name='teams',
            field=models.ManyToManyField(to='teams.Contestant', verbose_name='Uczestnicy'),
        ),
        migrations.AlterField(
            model_name='match',
            name='outcome',
            field=models.CharField(choices=[('N', 'N'), ('1', '1'), ('2', '2'), ('X', 'X')], default='N', max_length=1, verbose_name='Rezultat'),
        ),
    ]
