# Generated by Django 3.1.3 on 2020-11-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_match_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='Ukończony'),
        ),
    ]
