# Generated by Django 3.1.3 on 2020-11-15 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_tournament_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='teams',
        ),
        migrations.AddField(
            model_name='tournament',
            name='contestants',
            field=models.ManyToManyField(blank=True, to='teams.Contestant', verbose_name='Uczestnicy'),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='teams.country', verbose_name='Kraj pochodzenia'),
        ),
    ]
