# Generated by Django 3.1.3 on 2020-11-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_auto_20201115_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='sport',
            field=models.CharField(choices=[('FOOTBALL', 'Piłka nożna'), ('VOLLEYBALL', 'Siatkówka'), ('TENNIS', 'Tenis')], default='FOOTBALL', max_length=15, verbose_name='Dyscyplina'),
        ),
    ]
