# Generated by Django 3.1.3 on 2020-11-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_contestant_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='Zakończony'),
        ),
    ]
