# Generated by Django 3.1.3 on 2020-12-08 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0004_auto_20201122_1540'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nazwa')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data dodania')),
                ('contestants', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Uczestnicy')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.tournament', verbose_name='Zawody')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data dodania')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.match', verbose_name='Mecz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
