# Generated by Django 3.1.3 on 2020-12-08 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('betting', '0001_initial'), ('betting', '0002_auto_20201208_1228'), ('betting', '0003_auto_20201208_1234')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0004_auto_20201122_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data dodania')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.match', verbose_name='Mecz')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Użytkownik')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
