# Generated by Django 3.1.3 on 2020-12-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='playerOnePrediction',
            field=models.PositiveIntegerField(default=0, verbose_name='Wynik zawodnika 1'),
        ),
        migrations.AddField(
            model_name='bet',
            name='playerTwoPrediction',
            field=models.PositiveIntegerField(default=0, verbose_name='Wynik zawodnika 2'),
        ),
    ]
