# Generated by Django 3.1.3 on 2020-12-08 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0003_participant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ('-points',)},
        ),
    ]
