# Generated by Django 3.1.3 on 2020-12-10 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0004_auto_20201208_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='contestants',
        ),
        migrations.AddField(
            model_name='participant',
            name='league',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='betting.league', verbose_name='Liga obstawiania'),
            preserve_default=False,
        ),
    ]
