# Generated by Django 3.1.3 on 2021-01-03 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0006_auto_20201210_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='leagueKey',
            field=models.CharField(default='8CFAAA', max_length=30, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='betting.league', verbose_name='Liga obstawiania'),
        ),
    ]
