# Generated by Django 3.1.3 on 2021-01-03 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0007_auto_20210103_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='leagueKey',
            field=models.CharField(default='E9FE77', max_length=30, unique=True, verbose_name='Key'),
        ),
    ]
