# Generated by Django 3.1.3 on 2021-01-05 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_auto_20210103_1911'),
        ('betting', '0008_auto_20210104_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='valid',
            field=models.BooleanField(default=False, verbose_name='Ważność'),
        ),
        migrations.AlterField(
            model_name='league',
            name='leagueKey',
            field=models.CharField(default='1EF1A4', max_length=30, unique=True, verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='league',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='betting_leagues', to='teams.tournament', verbose_name='Zawody'),
        ),
    ]
