# Generated by Django 3.1.3 on 2021-01-05 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_auto_20210106_0003'),
        ('betting', '0009_auto_20210105_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='cashout',
            field=models.BooleanField(default=False, verbose_name='Czy policzony'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='teams.match', verbose_name='Mecz'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='betting.participant', verbose_name='Członek ligi'),
        ),
        migrations.AlterField(
            model_name='league',
            name='leagueKey',
            field=models.CharField(default='FEFDD7', max_length=30, unique=True, verbose_name='Key'),
        ),
    ]
